export {
  platformClient,
  platform,
  getPlatformClient,
  getCurrentUser,
  signIn,
  signUp,
  signOut,
  resetPassword,
  updatePassword,
  fetchData,
  insertData,
  updateData,
  deleteData,
  subscribeToChanges,
  unsubscribeFromChanges,
  uploadFile,
  getPublicUrl,
  STORAGE_BUCKETS,
  BUCKET_FOLDERS,
  createStorageBucket,
  listBuckets,
  getBucket,
  updateBucket,
  checkUserExists,
  query,
  execute,
  adminApi,
  ensureAuthenticated,
  sanitizeProfileData,
  mapUserType,
  saveProfile,
  getProfileById,
  getProfileByUserId,
  upsertData,
  selectData,
  storage,
  auth,
  rpc
} from './platformClientCore';

export { platformClient as default } from './platformClientCore';
