export {
  platformClient,
  platform,
  getPlatformClient,
  getActiveTenantId,
  setActiveTenantId,
  clearActiveTenantId,
  getCurrentUser,
  signIn,
  signUp,
  signOut,
  resetPassword,
  updatePassword,
  fetchData,
  selectData,
  insertData,
  upsertData,
  updateData,
  deleteData,
  uploadFile,
  getFileUrl,
  getPublicUrl,
  deleteFile,
  createStorageBucket,
  listBuckets,
  getBucket,
  updateBucket,
  checkUserExists,
  query,
  execute,
  inviteUser,
  inviteTeamMember,
  toDatabaseFormat,
  storage,
  auth,
  rpc
} from './platformClientCore';

export { platformClient as default } from './platformClientCore';
